name: Deploy para Vercel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Deploy para Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

